# Change baseurl before deploy
baseurl = "https://enigma-soul.github.io/Blog"
languageCode = "zh-cn"
title = "Enigma_Soul"

# 主题i18n支持。
# 可用值：en、fr、id、ja、ko、pt-br、zh-cn、zh-tw、es、de、nl、th、el、uk、ar
defaultContentLanguage = "zh-cn"

# 如果 DefaultContentLanguage 在 [zh-cn ja ko] 中，请将 hasCJKLanguage 设置为 true。
# 这将创造。摘要和。WordCount 在中日韩语言中表现正常。
hasCJKLanguage = true

# 在使用之前把它改成你的Disqus短名
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5